#!/bin/bash

BLUE_COLOR='\033[0;34m'
GREEN_COLOR='\033[0;32m'
NO_COLOR='\033[0m'

function print_message {
  local COLOR=$GREEN_COLOR
  if [ "$2" == "blue" ]; then
    COLOR=$BLUE_COLOR
  fi
  echo -en "${COLOR}${1}${NO_COLOR}"
}

# get FOLDER_NAME and create & enter
#printf '%sFolder Name: %s' "$GREEN_COLOR" "$NO_COLOR"
print_message "Folder Name: "
read -r FOLDER_NAME
mkdir -p "$FOLDER_NAME"

# get episode numbers
#printf "$GREEN_COLOR""Episode Number: ""$NO_COLOR"
print_message "Episode Number: "
read -r EPISODE_NUMBER

#if episodes was 1 then download it with wget
#otherwise get link with flag then replace number episodes for download
cd "$FOLDER_NAME" || exit
if [ $((EPISODE_NUMBER)) -gt 1 ]; then
  #printf "$GREEN_COLOR""Link with flag EPISODE: ""$NO_COLOR"
  print_message "Link with flag EPISODE: "
  read -r MLINKS
  for ((epn = 1; epn <= $((EPISODE_NUMBER)); epn++)); do
    epNumber=$(printf %02d $epn)
    #wget -c "$(echo $MLINKS | sed "s/EPISODE/$epNumber/")"
    wget -c "${MLINKS//EPISODE/$epNumber}"
  done

else
  #printf "$GREEN_COLOR""Link: ""$NO_COLOR"
  print_message "Link: "
  read -r SLINK
  wget -c "$SLINK"
fi

# exist folder
cd ..
