#!/bin/bash

BLUE_COLOR='\033[0;34m'
GREEN_COLOR='\033[0;32m'
NO_COLOR='\033[0m'

function print_message {
  local COLOR=$GREEN_COLOR
  if [ "$2" == "blue" ]; then
    COLOR=$BLUE_COLOR
  fi
  echo -en "${COLOR}${1}${NO_COLOR}"
}

# get FOLDER_NAME and create & enter
print_message "Folder Name: "
read -r FOLDER_NAME
mkdir -p "$FOLDER_NAME"

# get episode numbers
print_message "Episode Number: "
read -r EPISODE_NUMBER

#if episodes was 1 then download it with wget
#otherwise get link with flag then replace number episodes for download
cd "$FOLDER_NAME" || exit
rm -rf 'links'
if [ $((EPISODE_NUMBER)) -gt 1 ]; then
  print_message "Link with flag EPISODE: "
  read -r MLINKS
  for ((epn = 1; epn <= $((EPISODE_NUMBER)); epn++)); do
    epNumber=$(printf %02d $epn)
    NEW_LINK=${MLINKS//EPISODE/$epNumber}
    echo "$NEW_LINK" >>'links'
    wget -c "$NEW_LINK"
  done

else
  print_message "Link: "
  read -r SLINK
  echo "$SLINK" >>'links'
  wget -c "$SLINK"
fi

# exist folder
cd ..
